/** Analysis page — reuses Create / Results button + tab tokens. */

export {
  RESULTS_VIEW_TAB,
  RESULTS_VIEW_TAB_ACTIVE,
  RESULTS_VIEW_TAB_IDLE,
} from "./resultsTypography";

export {
  CREATE_ACCENT_OUTLINE_BUTTON,
  CREATE_ACCENT_OUTLINE_BUTTON_COMPACT,
  CREATE_DASHED_ADD_BUTTON,
  CREATE_GHOST_BUTTON_BLOCK,
  CREATE_LINK_TEXT_BUTTON,
  CREATE_LINK_TEXT_BUTTON_UNDERLINE,
  CREATE_OUTLINE_BUTTON,
  CREATE_OUTLINE_BUTTON_SHADOW,
  CREATE_PUBLISH_BUTTON,
} from "./createTypography";
